### ISSUE TITLE
Not so nice gradient in Safari - div id rich-workspace

### ISSUE THREAD

**Issue by TomGem** [mwalbeck/nextcloud-breeze-dark#189] opened 2020-12-03 12:29 UTC
First of all, after years of using Nextcloud I just discoverd your theme. 
I've really missed something, it's beautiful, thank you!

Second, I manage an instance (version 20.0.2) with a lot of Safari clients (really a lot).

There is a not so nice gradient in Safari within the div with id `rich-workspace`, the place where you can edit the _Readme.md_:

<img width="1678" alt="Safari_gradient-rich-workspace" src="https://user-images.githubusercontent.com/8806191/101017377-4bd52f00-356a-11eb-9106-4cb2b8eef69a.png">

If I disable the style manually it looks better:

<img width="1678" alt="Safari_gradient-rich-workspace_manually_disabled" src="https://user-images.githubusercontent.com/8806191/101017529-7b843700-356a-11eb-84ac-2a90d96783e0.png">

The gradient is applied from `apps/files/js/files.js` and looks fine with a light theme, but not so with a dark.

Do you think you can do something about that in your theme styles?

**Comment by TomGem** [comment] 2020-12-08 15:02
Jfyi, other browsers but Firefox show the same gradient. 
Therefore I've installed the app _Custom CSS_ to overwrite the gradient from apps/text.

The CSS:
```
/* remove the gradient from apps/text, it looks strange with dark themes */
#rich-workspace:not(.focus):not(.icon-loading):after {
  background-image: none !important;
}
/* hide the scrollbar-corner */
::-webkit-scrollbar-corner {
  color: var(--color-border-dark) transparent !important;
}
```

**Comment by mwalbeck** [comment] 2020-12-08 17:08
Thanks for the update, I'll get it fixed in the next release.

**Comment by mwalbeck** [comment] 2020-12-13 12:44
I have tried to reproduce this issue with chromium, but I haven't been able to. The gradient works as intended and is barely noticeable. This might also be platform specific. You mentioned other browsers showed the gradient, which browser other than safari can you reproduce this issue with? And have you been able to reproduce this on a linux or windows machine or are you in a position to try?

The gradient in your screenshot is definitely rendered wrong, so I'd prefer to find a workaround for that instead of just removing it, but I don't have access to any mac systems to reproduce the issue.

Also have you tried to see if the issue is present with the official nextcloud dark theme? I would assume it is, as I don't really change any styling related to that part, but it's worth a shot.

**Comment by TomGem** [comment] 2020-12-14 13:40
Mmm, I just tried to reproduce it on different browsers on macOS but haven't been able to. On the other hand I do have a 6 days old screenshot of Chrome showing the same gradient. Maybe I was playing with the wrong css at that moment?  My bad, the 'not so nice gradient' is just there with Safari (as in the title), so it is an issue with Safari only. And yes, the dark theme shows the same gradient in Safari. 

I'm in a special situation with a lot (>70%) Safari users here.
However, I wouldn't break your theme for them if I'd be you. 
I'm good with my 'Custom CSS' hot fix for my users. 

Maybe just wait? If it really is a Safari problem it will be fixed someday. 
Though unlikely, but if it's a problem with Nextcloud CSS other browsers will start to show the same behaviour too.
Both scenarios have happened in the past. ;)

**Comment by mwalbeck** [comment] 2020-12-14 20:41
Thanks for the update. Okay, then it's most likely a CSS rendering issue in Safari. And yeah this theme is probably not the correct place to fix the issue, even if I had access to Mac hardware. I agree, the best solution would definitely be for it to get fixed in Safari. That or the issue can be reported to upstream Nextcloud and a possible workaround can be found there, which would apply to both the upstream dark theme and this one.

With that in mind I'll go ahead and close this issue. Thank you for the taking the time to report the issue. Let me know if you run into any other problems.

**Closed by mwalbeck** 2020-12-14 20:41 UTC
Labels: bug
