### ISSUE TITLE
Please style the Deck app

### ISSUE THREAD

**Issue by jakobroehrl** [mwalbeck/nextcloud-breeze-dark#130] opened 2020-05-13 05:57 UTC
**Which app would you like to have styled**:
Deck

![grafik](https://user-images.githubusercontent.com/24530680/81776528-3e355a80-94ef-11ea-9c35-3600ad74668d.png)

![grafik](https://user-images.githubusercontent.com/24530680/81776546-48575900-94ef-11ea-9681-7ac94f88b0a2.png)

![grafik](https://user-images.githubusercontent.com/24530680/81776593-61600a00-94ef-11ea-9cf7-45c6bc54dec9.png)

**Your setup (please complete the following information):**
NC 18.0.4

**Comment by mwalbeck** [comment] 2020-05-13 08:47
Already planned, this currently has top priority. Duplicate of #126

**Closed by mwalbeck** 2020-05-13 08:47 UTC
Labels: styling request

**Comment by jakobroehrl** [comment] 2020-05-13 08:50
Thanks! Sorry about the duplicate
