### ISSUE TITLE
Background image not showing when Nextcloud runs in sub folder of domain

### ISSUE THREAD

**Issue by efelon** [mwalbeck/nextcloud-breeze-dark#97] opened 2020-02-18 11:07 UTC
**Describe the bug**
When running the nextcloud installation in a sub folder of the domain (mydomain.de/nc) the background image for the login is not displayed.

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.1
 - Theme version: 18.0.6
 - Browser and browser version Firefox, Chrome, ...

**Additional context**
When I manually add the subfolder "**nc**" to the **guest.css** like this, it is working:

```
#body-login {
    background-image:
        url('/nc/apps/theming/image/background'),
        url('/core/img/background.png') !important;
   [...]
}
```
_(original url: /apps/theming/image/background)_

The styles from the regular theming show already the correct path but get overwritten by the guest.cc.

**Comment by mwalbeck** [comment] 2020-02-18 20:34
Thanks for reporting this. It'll probably make sense to specify the custom background location as a relative path instead of absolute. I'll have a look and get it fixed.

**Comment by efelon** [comment] 2020-02-18 21:10
Yor're welcome, I'm happy to help. Let me add a little observation, although I'm not sure it is even related.
When visiting the nextcloud login page. At first for a few milliseconds (depending on your network connection I assume) the custom "Theming Color" is shown before the background image is loaded. Maybe you have some ideas if this can be fixed as well.

**Comment by mwalbeck** [comment] 2020-02-24 00:06
I've have changed the background paths to relative ones, which should hopefully fix it. it will be in the next release, hopefully, out sometime this upcoming week.

I also had a look at the background colour on the login screen. I changed it so the background-color is always the main background for the theme, and therefore should look less out of place.

**Comment by mwalbeck** [comment] 2020-02-24 00:11
Actually while I'm working on another issue for the upcoming release, could you verify my change works as intended? I've changed the path to

`../../../apps/theming/image/background`

**Comment by efelon** [comment] 2020-02-24 05:24
@mwalbeck Yes and thanks, this path works. If you can test it with a installation in the webroot, then this can be closed.

**Comment by mwalbeck** [comment] 2020-02-24 18:30
Great, thanks for testing. It works as intended with with a webroot setup. I'll go ahead and close the issue when the next release is published.

**Comment by mwalbeck** [comment] 2020-02-25 18:29
New release has just been published.

**Closed by mwalbeck** 2020-02-25 18:29 UTC
Labels: bug
