### ISSUE TITLE
Dark and non-dark icons in the admin panel

### ISSUE THREAD

**Issue by L0g4n** [mwalbeck/nextcloud-breeze-dark#31] opened 2018-08-31 10:45 UTC
After updating to Nextcloud 13.0.6 and updating the theme to version 13.0.5 and with Chrome 68.0.3440.106 I experience dark icons mixed with non-dark icons in the admin panel.

Here's a screenshot:
![screenshot1](https://i.imgur.com/DFNLAHl.png)

**Comment by mwalbeck** [comment] 2018-09-03 05:45
Hi

I can't seems to reproduce the same problem, but I've noticed that the icons that are black are all icons that should be taken from the theme directly. The white icons are all icons I couldn't easily replace so I'm changing their color with CSS.

Have you disabled the theming app? The theming app is the only thing I know for sure causes this kind of problem with custom themes.

**Comment by L0g4n** [comment] 2018-09-04 13:58
Hi,

thanks for your answer. No, i've disabled the theming app since I first installed this theme - and I double checked that it is still not activated (so the nextcloud update did not activate it again).

**Comment by mwalbeck** [comment] 2018-09-06 14:54
Okay, have you noticed any other places in Nextcloud where there are dark icons. I don't have a great understanding of the inner working of how Nextcloud handles custom themes. Stuff like the details of exactly how Nextcloud handles replacing icons, because so far it has more or less worked. I have experienced issues like yours, but only while using my development setup, which I just reinstalled to fix it.

The main problem is there isn't really any good documentation on the more specific details for custom themes, and I sadly don't have time to dig through the code. Though there is one thing you could do that might be a help, if you inspect the HTML and let me know the source (src) of the dark icons.

I'll keep an eye out and see if I find something.

**Comment by smirkybg** [comment] 2018-11-01 07:57
Nextcloud 14.0.3 with theme version 14.0.2 from zip.
[Click for screenshot](https://smirky.net/upload/storage/20181101_095554_theme_nextcloud.png).
The problem remains.

**Comment by mwalbeck** [comment] 2018-11-01 08:51
Hi, thanks for the update. 

First, have you tried clearing your browsers cache? See if that works. If not, could I ask you to open the HTML inspection tool and take a screenshot of the source of the image and the CSS that's applied to it. Then I can maybe figure out what's going on.

**Comment by smirkybg** [comment] 2018-11-01 09:17
Not sure which part of CSS you need. I'm not an expert in CSS, so you will have to be more specific.
I did take a screenshot though, not sure if it's helpful. [Click.](https://www.smirky.net/upload/storage/20181101_111256_screenshot.png)

**Comment by mwalbeck** [comment] 2018-11-03 05:15
Thanks for the screenshot. I can see from it that Nextcloud is taking the icons from the wrong location. It's taking the icons from the app folder instead of from the theme, which is why it's black. I'm not sure of the reason for this as I don't know all the different things Nextcloud looks for to decide which icon to use. The only thing I'm certain of is when it works as intended icons from custom themes get priority.

You can try running the occ command **maintenance:theme:update** and see if that works.

**Comment by smirkybg** [comment] 2018-11-03 11:36
0 « root » /usr/share/webapps/nextcloud # sudo -u http ./occ maintenance:theme:update
The current PHP memory limit is below the recommended value of 512MB.
mimetypelist.js is updated
Image cache cleared


The result is still the same.

**Comment by 0E800** [comment] 2019-01-02 10:20
```
<a href="/settings/user/sharing">
<img alt="" src="/themes/nextcloud-breeze-dark/core/img/actions/share.svg">
<span>Sharing</span>
```
										
The reason is because the icon in black are not being requested from the themes directory.

![Imgur](https://i.imgur.com/JzFGc25.png)
```
<a href="/settings/user/ojsxc">
<img alt="" src="/apps/ojsxc/img/app-black.svg">
<span>JavaScript XMPP Client</span>
```

**Comment by mwalbeck** [comment] 2019-04-10 04:49
Okay, a similar issue is now showing on my personal instance of Nextcloud so I can try to troubleshoot it a bit better. I have problems with the Favicon and the settings dropdown icons. What I've noticed so far with the favicon is, depending on which app I'm using, it switches back and forth between pulling the favicon from the theme and core.

**Comment by mwalbeck** [comment] 2019-04-23 09:30
Before I had a chance to do more in-depth testing the problem fixed itself on my personal instance, which validates my theory that it most likely is a caching issue.

**Comment by xf-** [comment] 2019-05-14 14:56
Nice work, but maybe color the icons with css

**Comment by mwalbeck** [comment] 2019-07-27 11:46
A quick little update, I had this issue recently which I fixed by running the **maintenance:repair** occ command. Though be a bit a careful when using it, it seems to work fine with a standard install, but the docker image didn't like it. It seems the cache isn't regenerated properly in the docker image, but redoing the container should fix it.

**Comment by tanghus** [comment] 2019-11-16 10:49
Great theme, @mwalbeck :+1: 
I just installed it, but now also notice, that the favicons shown are always the same standard Nextcloud icons, instead of the apps own icon. I have several Nextcloud tabs pinned in Firefox, so I only see the favicon, and this makes it difficult to tell which is which.

**Comment by mwalbeck** [comment] 2019-11-16 21:09
Thanks a lot @tanghus 

I'm not quite sure, if it's possible, at this time, but I would be interested in implementing it, if and/or when it's doable. I'll have a look and see what the options are.

I would greatly appreciate, if you opened a separate issue. It makes it easier to keep track of everything.

**Comment by tanghus** [comment] 2019-11-16 22:24
> I would greatly appreciate, if you opened a separate issue. It makes it easier to keep track of everything.

#76

**Comment by mwalbeck** [comment] 2020-01-26 17:59
I'm going to close this issue as it's related to caching problems of image files. The versions for both NC17 and NC18 no longer use actual image files for icons, but everything is handled in CSS. You're very welcome to open up a new issue if any of you experience similar issues with the new versions of this theme.

**Closed by mwalbeck** 2020-01-26 17:59 UTC
