### ISSUE TITLE
Getting a range of 500 and 404 after activating the theme

### ISSUE THREAD

**Issue by SuperSandro2000** [mwalbeck/nextcloud-breeze-dark#94] opened 2020-02-12 04:14 UTC
**Describe the bug**
After activating the breeze dark app I get the following 500 and 404 in my browser console.
````
index.js:1200 GET https://nextcloud.example.de/apps/theming/image/background 404
index.js:1200 GET https://nextcloud.example.de/apps/theming/image/background 404
index.js:1200 GET https://nextcloud.example.de/svg/news/rss?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/mail/drafts?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/mail/sent?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/mail/archive?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/volume?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/repeat?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/pause?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/deck/deck?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/previous?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/next?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/mail/junk?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/play?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/mail/star?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/circles/circles?color=f2f2f2&v=1 500
index.js:1200 GET https://nextcloud.example.de/svg/audioplayer/shuffle?color=f2f2f2&v=1 500
````

**To Reproduce**
1. Activate the app
2. Go to the file overview
3. Open dev tools and the console to find the log

**Expected behavior**
Don't request resources if they don't exist to not flood logs with false positives

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.0
 - Theme version 18.0.5
 - Browser and browser version Chrome 79

**Additional context**

I have not set a custom background in the theme app and I don't have the news, mail, audioplayer, deck or circles app installed.

**Comment by mwalbeck** [comment] 2020-02-12 20:05
I'm going to have to look a bit closer into this, as this is definitely not intended. Firstly, I can say that a 404 error for a custom background, when one isn't used, is currently expected behavior, but only on the login screen. The reason for this is that I have no logic in the theme other than what sass can do so it's the only way I've found to support backgrounds.

For all the app icons, I don't know why they would show up in the browser logs. Currently I'm including all icons in the theme because I don't have any logic that is aware of what apps are installed on your Nextcloud instance. This shouldn't be a problem though, because with icons, Nextcloud takes my icon definitions and compiles into one big file with it's own icon definitions. So if a icon isn't available, it won't be included in the stylesheet served to the user.

Have you been able to reproduce this several times? If yes, can you try and run **occ maintenance:repair** and see if it still happens?

**Comment by SuperSandro2000** [comment] 2020-02-14 12:34
When I reported the bug I could reproduce it with ease but when I tried it again today I can't reproduce it. Maybe it was some weird caching issue?

**Comment by mwalbeck** [comment] 2020-02-14 17:52
With that in mind, I think it's likely that an issue happened during Nextclouds sass compilation, which led to it caching the not quite fully compiled stylesheets. That would then have led to you experiencing this issue until the cache was rebuild. Since you can't reproduce it anymore, it's hopefully just a one-off bug. If it happens again **occ maintenance:repair** will most likely fix it, based on the info you provided. Hopefully it isn't, but if it's a recurring thing, do let me know, and we can see if we can figure out what's causing it.

**Comment by mwalbeck** [comment] 2021-01-17 17:12
I'm going to assume this hasn't happened since so I'm going to close the issue for now. You're welcome to reopen it if it happens again.

**Closed by mwalbeck** 2021-01-17 17:12 UTC
Labels: bug
