### ISSUE TITLE
Email Text barely visible

### ISSUE THREAD

**Issue by HannesJo0139** [mwalbeck/nextcloud-breeze-dark#196] opened 2021-01-06 22:47 UTC
This seems related to https://github.com/mwalbeck/nextcloud-breeze-dark/issues/190

Some emails are displayed with nearly white background and so the text is not visible/readable any longer.

-   Nextcloud version: 20.0.4
-   Theme version: 20.0.2
-   Browser and browser version: Firefox 84, Chrome 87

I forwarded the email to your account adress.

![Screenshot from 2021-01-06 23-30-59_bl](https://user-images.githubusercontent.com/42114183/103827291-f3b5af00-5078-11eb-8732-1965ffcb2393.png)

**Comment by it-open** [comment] 2021-01-12 13:31
In the html from the iframe the style --color-main-text: #222; will be changed to --color-main-text: rgba(239, 240, 241, 1); but the Email still has white Background. I would prefer no to change the Background and leave the Text as before.

**Comment by JasperCiti** [comment] 2021-01-13 05:11
I also experience the same issue. Any updates on this?

**Comment by it-open** [comment] 2021-01-13 07:19
Im just a User. But to my opinion its more a problem in the Mail App than here in Breeze Dark. This plugin redefines the Color Values in CSS. But the Mail App uses this to Change a Text Color in the Mail (Hardcoded in the html Tag of the Iframe fro the Mail).
Normally it will define a Text Color of #222. Breeze Dark has no control over the Iframe (and my to cents shoudnt) but changes the Color of text to a lighter Version of rgba(239,240,241,1). So you will have light text on dark Bg. The Mail app uses this color to set the Text Color of the Email and as Long as the Email does not define its own color will not change. Thats why you will get Light text on Light bg.  Could someone from Breeze-Dark file a Bug in the Email App?

**Comment by HannesJo0139** [comment] 2021-01-13 13:20
Hmm so we might open an issue there. Maybe @mwalbeck can say anything about it?

**Comment by mwalbeck** [comment] 2021-01-13 15:15
Sorry, I have been quite busy so I haven't had a chance to reply yet, but I have had a look at the issue.

The problem is with the text colour as I'm going to keep the background a light colour because that is generally the assumption of most email that don't have a background colour set. So the fix for #190 breaks any emails that don't have a font colour set, but I currently assume that there are fewer of those than emails that don't have a background colour set.

As @it-open notes the default text colour for the iframes used to show html emails is dark and is changed to light when the Breeze Dark theme is used. This is not controlled by the theme but by the Mail app itself. The way it works is when a html email is loaded the Mail app looks at the root styling for the current page and gets the default text colour which it then passes along to the iframe. It is dynamically done but because it takes the value from the root's styling I can't realistically change it as it would change the default text colour for all of Nextcloud. It is the same issue with #183.

So @HannesJo0139, it's pretty much the same issue in that currently not all html emails can be shown properly. I have just chosen to properly show the emails that the official dark theme currently doesn't.

There isn't really a good fix I can make at this point in time, so this is definitely some that should be fixed upstream. However they choose to fix it, I can then adapt the Breeze Dark theme to that fix. Also there is already an open issue regarding this over at the Mail app https://github.com/nextcloud/mail/issues/1742

**Comment by HannesJo0139** [comment] 2021-01-13 15:51
Thanks for clarification!

**Comment by mwalbeck** [comment] 2021-02-18 21:29
This has now been fixed in Mail 1.8.2 and I have adjusted the styling slightly in the theme so it better fits the new fix.

**Closed by mwalbeck** 2021-02-18 21:29 UTC
Labels: bug, upstream
